### ISSUE TITLE
about input data

### ISSUE THREAD

**Issue by BrisksHan** [linhongseba/Temporal-Network-Embedding#3]
Thank you for the excellent work. 

Regarding the input of dynamic networks,  should the number of nodes be fixed for all dynamic networks, even if some nodes do NOT exist in some networks.

**Comment by linhongseba** [comment]
Dear Han,
The number of nodes is OK to not to be fixed for each snapshot. The code reads and finds the maximum number of nodes across all the snapshots, and all the related data structures are initialized using the maximum number of nodes

**Comment by BrisksHan** [comment]
Thank you !
